const ADD_COURSE = "ADD_COURSE";
const ADD_COURSE_BEGIN = "ADD_COURSE_BEGIN";
const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS";
const ADD_COURSE_ERROR = "ADD_COURSE_ERROR";
const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";

const LOAD_COURSES_BEGIN = "LOAD_COURSES_BEGIN";
const LOAD_COURSES_ERROR = "LOAD_COURSES_ERROR";

export {
  ADD_COURSE,
  ADD_COURSE_BEGIN,
  ADD_COURSE_SUCCESS,
  ADD_COURSE_ERROR,
  LOAD_COURSES_SUCCESS,
  LOAD_COURSES_BEGIN,
  LOAD_COURSES_ERROR
};
